### ISSUE TITLE
FE > Metadata

### ISSUE THREAD

**Issue by JessK89** [typecode/typester#93]
It looks like no metadata for search engines or social media or even page title are appearing in the <head> yet.  Obviously, this is just a bug/oversight, but can we please get this data pushed into head?  Also, please let me know when this is done since I need it for the GA integration.

Huge thanks!

**Comment by JessK89** [comment]
Damnit, slipped and assigned to wrong project, sorry!

**Comment by ssyberg** [comment]
duplicate
